spring.application.name=salon-backend

server.port=9209

spring.datasource.url=jdbc:postgresql://localhost:5432/website
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:change-this-dev-secret-to-a-long-random-value-before-production-use}
app.jwt.expiration-ms=86400000

app.storage.type=local
app.upload.dir=uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.cors.allowed-origins=http://localhost:4200

app.admin.default-username=admin
app.admin.default-password=Admin@123

# Email notifications (SMTP)
app.notifications.email.enabled=true
#app.notifications.email.from=no-reply@radiancesalon.com
app.notifications.email.from=softwaredeveoper2026@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=softwaredeveoper2026@gmail.com
spring.mail.password=ylms rgfa acsp dakf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# WhatsApp Cloud API notifications
app.notifications.whatsapp.enabled=true
app.notifications.whatsapp.api-version=v21.0
app.notifications.whatsapp.phone-number-id=1283406458186561
app.notifications.whatsapp.access-token=EAAO8zqgtTsABSOCcElJLjDKhNhtsMhLIcr0Gb6ToXYLi14cqlme1h6rZAKBDwS5TwNZCMLQI55fBWwqxv9prMN48GCGkXpy1kCWlKOHKMQnT4qSc2VNOGUpuYX26ZCnrrNsJSCWApeRYoDjued2nJVPPO8KymFE4iZAzqXZCMPanVCLBmCPeo1PCE0DyeFtMdbZCsGz24i6RXz1TKhj7tq4FdtoLyLYtJCXjhZCki1zfZCrCXBGyaNAqZCSERwAQ1PPs7yqsFPvnYZBRqtPsUfRGqZAm1LW
app.notifications.whatsapp.default-country-code=91
